modLoader="javafml"
loaderVersion="[28,)"
[[mods]]
modId="moveplus"
version="${file.jarVersion}"
displayName="Move Plus"
authors="Corosus"
description='''
Makes you do the move thing more
'''

[[dependencies.moveplus]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="CLIENT"
[[dependencies.moveplus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="CLIENT"
