modLoader="javafml"
loaderVersion="[34,)"
license = "All Rights Reserved"
[[mods]]
modId="ltmoveplus"
version="${file.jarVersion}"
displayName="Move Plus - Love Tropics Crawl Anywhere"
authors="Corosus"
description='''
Steve go brrr in the tropics
'''