modLoader="javafml"
loaderVersion="[40,)"
license = "All Rights Reserved"
[[mods]]
modId="moveplus"
version="${file.jarVersion}"
displayName="Move Plus"
authors="Corosus"
description='''
Steve go brrr
'''